apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: school-application
  namespace: argocd
spec:
  project: school-project
  source:
    repoURL: https://github.com/ebad-arshad/MERN-School-Management-System.git
    targetRevision: k8s
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: smp
  syncPolicy:
    automated:
      prune: true       # delete removed manifests
      selfHeal: true    # fix drift automatically
    syncOptions:
      - CreateNamespace=true
