services:
  school-frontend:
    image: school-frontend
    container_name: school-frontend
    build: ./frontend/
    ports:
      - 80:80
    networks:
      - school-net
    restart: always
  school-backend:
    image: school-backend
    container_name: school-backend
    build: ./backend/
    networks:
      - school-net
    restart: always
    depends_on:
      mongo:
        condition: service_healthy
  mongo:
    image: mongo:latest
    container_name: mongo
    networks:
      - school-net
    restart: always
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - mongo-data:/data/db

networks:
  school-net:
volumes:
  mongo-data: