apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: school-backend-hpa
  namespace: smp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: school-backend
  minReplicas: 1
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
