apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: smp
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/data"