apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: smp
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  selector:
    matchLabels:
      app: mongo
  serviceName: "mongo"
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:8
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: database
              key: root_username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database
              key: root_password
        - name: MONGO_INITDB_DATABASE
          valueFrom:
            secretKeyRef:
              name: database
              key: db
        volumeMounts:
        - name: mongo-storage
          mountPath: /data/db
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 10
          periodSeconds: 5
          
      volumes:
      - name: mongo-storage
        persistentVolumeClaim:
          claimName: mongo-pvc
